macro(my_macro arg1 arg2)
  message("Inside macro")
endmacro()

if(BUILD_TESTS)
  add_executable(testApp "test.cpp")
endif()

if(DO_STUFF)
  add_executable(testApp2 "test2.cpp")
elseif(DO_OTHER_STUFF)
  add_library(testLib STATIC "lib.cpp")
else()
  add_subdirectory("subdir")
endif()
